{% set name = "pyre" %}
{% set version = "1.10.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://github.com/pyre/pyre/archive/v{{ version }}.tar.gz
    sha256: c15bd41d1cef78073ba375e3a3cfa0c7e39b1ba4cc220c8ebef8df942978747e
    patches:
        # Hard-coded version, since the auto-versioning requires a cloned repo
      - pyre_version.patch

build:
  number: 0
  skip: true  # [win or py2k or python_impl == 'pypy']

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - make  # [unix]
  host:
    - python
    - zip
  run:
    - python

test:
  imports:
    - pyre
    - journal

about:
  home: http://pyre.orthologue.com
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: A Python framework for scientific applications

  description: |
    An open source application framework for building
    scalable, user-friendly scientific applications.

  dev_url: https://github.com/pyre/pyre
  doc_url: http://pyre.orthologue.com/docs

extra:
  recipe-maintainers:
    - aivazis
    - rtburns-jpl
