{% set name = "pyre" %}
{% set version = "1.12.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://github.com/pyre/pyre/archive/v{{ version }}.tar.gz
    sha256: b8b7461e27138d5cd8bd3d96894871790e34ee0c4f3b6d0882d5ef8cca2a612e
    patches:
        # Fallback clock stub for pre-10.12 SDK
      - macos-clock.patch
        # Fix missing file in cmake for bindings
      - fix-mem-bindings.patch

build:
  number: 0
  skip: true  # [win or py2k or python_impl == 'pypy']

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - pybind11                               # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - make  # [unix]
  host:
    - hdf5
    - pybind11
    - python
    - zip
  run:
    - python

test:
  requires:
    - cmake
  commands:
    # Disable TCP test on Docker
    # Reenable locale_codec after resolving https://github.com/pyre/pyre/issues/65
    - ctest --output-on-failure -E '(pyre.pkg.ipc.tcp.py|python.locale_codec.py|pyre.pkg.codecs.yaml_|pyre.lib.timers.process_timer|pyre.pkg.timers)'
  imports:
    - pyre
    - journal

about:
  home: http://pyre.orthologue.com
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: A Python framework for scientific applications

  description: |
    An open source application framework for building
    scalable, user-friendly scientific applications.

  dev_url: https://github.com/pyre/pyre
  doc_url: http://pyre.orthologue.com/docs

extra:
  recipe-maintainers:
    - aivazis
    - rtburns-jpl
