{% set name = "pyre" %}
{% set version = "1.11.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: http://pyre.orthologue.com/v{{ version }}.tar.gz
    sha256: f5f81bb7964a4a35fb098627ce8d78ffb2d9236a303627fac125a246b299e533
    patches:
        # Fallback clock stub for pre-10.12 SDK
        - macos-clock.patch
        # Promise minor version compatibility
        - version-compat.patch

build:
  number: 1
  skip: true  # [win or py2k or python_impl == 'pypy']

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - make  # [unix]
  host:
    - pybind11
    - python
    - zip
  run:
    - python

test:
  imports:
    - pyre
    - journal

about:
  home: http://pyre.orthologue.com
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: A Python framework for scientific applications

  description: |
    An open source application framework for building
    scalable, user-friendly scientific applications.

  dev_url: https://github.com/pyre/pyre
  doc_url: http://pyre.orthologue.com/docs

extra:
  recipe-maintainers:
    - aivazis
    - rtburns-jpl
